/* Generated by AN DISI Unibo */ 
package it.unibo.guibridge

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Guibridge ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var incineratorState = 2  // 0=Off, 1=On, 2=Idle
				var rpCount = 0
				var ashStorageFull = 0
				var robotX = 0
				var robotY = 0
				var robotJob = "Waiting Home"
				var lastUpdate = System.currentTimeMillis()
				var status = "NOT FULL"
				
				fun buildStateString(): String {
					return "incinerator=$incineratorState,rp=$rpCount,ash=$ashStorageFull,x=$robotX,y=$robotY,job=$robotJob,ts=$lastUpdate"
				}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("[$name] Initializing GUI Bridge")
						subscribeToLocalActor("incinerator") 
						subscribeToLocalActor("scale") 
						updateResourceRep( buildStateString()  
						)
						CommUtils.outcyan("[$name] Ready - http://localhost:8001/api/guibridge")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("ready") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t035",targetState="updateRpCount",cond=whenEvent("stateScale"))
					transition(edgeName="t036",targetState="updateAshStorage",cond=whenEvent("stateSonar"))
					transition(edgeName="t037",targetState="updateIncinerator",cond=whenEvent("burnEnd"))
				}	 
				state("updateRpCount") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stateScale(X)"), Term.createTerm("stateScale(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val weight = payloadArg(0).toInt()
												rpCount = weight / 50
												lastUpdate = System.currentTimeMillis()
								CommUtils.outcyan("[$name] RP count updated: $rpCount")
								updateResourceRep( buildStateString()  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("updateAshStorage") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stateSonar(X)"), Term.createTerm("stateSonar(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												ashStorageFull = payloadArg(0).toInt()
												lastUpdate = System.currentTimeMillis()
								if(  ashStorageFull == 1  
								 ){ status = "FULL" 
								}
								else
								 { status = "NOT FULL" 
								 }
								CommUtils.outcyan("[$name] Ash storage: $status")
								updateResourceRep( buildStateString()  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("updateIncinerator") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("burnEnd(BTIME)"), Term.createTerm("burnEnd(BTIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												incineratorState = 2
												lastUpdate = System.currentTimeMillis()
								CommUtils.outcyan("[$name] Incinerator -> Idle")
								updateResourceRep( buildStateString()  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
			}
		}
} 
