/* Generated by AN DISI Unibo */ 
package it.unibo.oprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Oprobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
			    val Posizioni: MutableMap<String, Array<String>> = mutableMapOf()
			    Posizioni["Home"] = arrayOf("0", "0")
			    Posizioni["BurnIn"] = arrayOf("2", "1")
			    Posizioni["BurnOut"] = arrayOf("4", "3")
				Posizioni["AshOut"] = arrayOf("5", "4")
				Posizioni["WasteIn"] = arrayOf("0", "4")
				var X="0"
				var Y="0"
				var Job=""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(100) 
						CommUtils.outred("Hello i'm $name")
						request("engage", "engage(name,325)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="home",cond=whenReply("engagedone"))
				}	 
				state("home") { //this:State
					action { //it:State
						CommUtils.outred("$name, i'm in HOME")
						
									X= Posizioni["Home"]!!.get(0)
									Y= Posizioni["Home"]!!.get(1)
									Job="Waiting_in_HOME"
						emitLocalStreamEvent("updateStateRobot", "update($X,$Y,$Job)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="goemptyincenerator",cond=whenDispatch("goBurnOut"))
					transition(edgeName="t04",targetState="gowastestorage",cond=whenDispatch("goWasteIn"))
				}	 
				state("gowastestorage") { //this:State
					action { //it:State
						
									X= Posizioni["WasteIn"]!!.get(0)
									Y= Posizioni["WasteIn"]!!.get(1)
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="goburnin",cond=whenReply("moverobotdone"))
					transition(edgeName="t06",targetState="gohome",cond=whenReply("moverobotfailed"))
				}	 
				state("goburnin") { //this:State
					action { //it:State
						CommUtils.outred("$name: arrivato al WASTEIN")
						
									X= Posizioni["WasteIn"]!!.get(0)
									Y= Posizioni["WasteIn"]!!.get(1)
									Job="in_WASTEIN"
						emitLocalStreamEvent("updateStateRobot", "update($X,$Y,$Job)" ) 
						forward("arrivoRobot", "p(X)" ,"scale" ) 
						
									X= Posizioni["BurnIn"]!!.get(0)
									Y= Posizioni["BurnIn"]!!.get(1)
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						delay(1500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="arrivedburnin",cond=whenReply("moverobotdone"))
					transition(edgeName="t08",targetState="gohome",cond=whenReply("moverobotfailed"))
				}	 
				state("arrivedburnin") { //this:State
					action { //it:State
						CommUtils.outred("$name: arrivato al BURNIN")
						
									X= Posizioni["BurnIn"]!!.get(0)
									Y= Posizioni["BurnIn"]!!.get(1)
									Job="in_BURNIN"
						emitLocalStreamEvent("updateStateRobot", "update($X,$Y,$Job)" ) 
						forward("robotArrived", "robotArrived(X)" ,"wis" ) 
						delay(1500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="gohome", cond=doswitch() )
				}	 
				state("goemptyincenerator") { //this:State
					action { //it:State
						
									X= Posizioni["BurnOut"]!!.get(0)
									Y= Posizioni["BurnOut"]!!.get(1)
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="goashout",cond=whenReply("moverobotdone"))
					transition(edgeName="t010",targetState="gohome",cond=whenReply("moverobotfailed"))
				}	 
				state("goashout") { //this:State
					action { //it:State
						CommUtils.outred("$name: arrivato a BURNOUT")
						
									X= Posizioni["BurnOut"]!!.get(0)
									Y= Posizioni["BurnOut"]!!.get(1)
									Job="withdraw_ash"
						emitLocalStreamEvent("updateStateRobot", "update($X,$Y,$Job)" ) 
						delay(1500) 
						
									X= Posizioni["AshOut"]!!.get(0)
									Y= Posizioni["AshOut"]!!.get(1)
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="waitinginstruction",cond=whenReply("moverobotdone"))
					transition(edgeName="t012",targetState="gohome",cond=whenReply("moverobotfailed"))
				}	 
				state("waitinginstruction") { //this:State
					action { //it:State
						delay(2000) 
						forward("endRoutine", "endRoutine(X)" ,"wis" ) 
						forward("endRoutine", "endRoutine(X)" ,"tester" ) 
						CommUtils.outred("$name arrivato a ASHOUT")
						
									X= Posizioni["AshOut"]!!.get(0)
									Y= Posizioni["AshOut"]!!.get(1)
									Job="ash_dropped"
						emitLocalStreamEvent("updateStateRobot", "update($X,$Y,$Job)" ) 
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="gowastestorage",cond=whenDispatch("goWasteIn"))
					transition(edgeName="t014",targetState="gohome",cond=whenDispatch("goHome"))
				}	 
				state("gohome") { //this:State
					action { //it:State
						
									X= Posizioni["Home"]!!.get(0)
									Y= Posizioni["Home"]!!.get(1)
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="home",cond=whenReply("moverobotdone"))
					transition(edgeName="t016",targetState="gohome",cond=whenReply("moverobotfailed"))
				}	 
			}
		}
} 
