/* Generated by AN DISI Unibo */ 
package it.unibo.datacleaner

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Datacleaner ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 	var DISTANCE = 0; 
				var LAST = 0;
				var DIFF = 0;
				var TOLERANCE = 5 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						subscribeToLocalActor("sonardevice") 
						CommUtils.outblue("$name subscribed to sonardevice")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="filter",cond=whenEvent("sonardata"))
				}	 
				state("filter") { //this:State
					action { //it:State
						CommUtils.outblack("$name distance=$DISTANCE")
						if( checkMsgContent( Term.createTerm("distance(DISTANCE)"), Term.createTerm("distance(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  DISTANCE = payloadArg(0).toInt()  
								CommUtils.outblack("$name distance=$DISTANCE")
								if(  LAST != 0 
								 ){ DIFF = (DISTANCE - LAST)  
								}
								else
								 { DIFF = TOLERANCE  
								 }
								if(  DISTANCE < 300 && ( DIFF >= TOLERANCE || DIFF <= -TOLERANCE )  
								 ){ LAST = DISTANCE  
								emitLocalStreamEvent("sonardata", "distance($DISTANCE)" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="filter",cond=whenEvent("sonardata"))
				}	 
			}
		}
} 
