/* Generated by AN DISI Unibo */ 
package it.unibo.sonardevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonardevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
			lateinit var reader : java.io.BufferedReader
			var working = false
		    lateinit var p : Process	
		    var Distance = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("$name | sonarstart")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="startTheSonar",cond=whenDispatch("sonarstart"))
					transition(edgeName="t010",targetState="stopTheSonar",cond=whenDispatch("sonarstop"))
				}	 
				state("stopTheSonar") { //this:State
					action { //it:State
						 working = false	 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="startTheSonar",cond=whenDispatch("sonarstart"))
					transition(edgeName="t012",targetState="stopTheSonar",cond=whenDispatch("sonarstop"))
					transition(edgeName="t013",targetState="endOfRead",cond=whenDispatchGuarded("doread",{ ! working  
					}))
				}	 
				state("startTheSonar") { //this:State
					action { //it:State
						
						    	working = true		
								p       = Runtime.getRuntime().exec("python sonar.py")
								reader  = java.io.BufferedReader(  java.io.InputStreamReader(p.getInputStream() ))	
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="readSonarData", cond=doswitch() )
				}	 
				state("readSonarData") { //this:State
					action { //it:State
						 
								var data = reader.readLine()
								CommUtils.outyellow("$name with python: data = $data"   ) 
								if( data != null ){
								try{ 
									val vd = data.toFloat()
									val v  = vd.toInt()
									if( v <= 100 ){	//A first filter ...
										Distance = v				
									}else Distance = 0
								}catch(e: Exception){
										CommUtils.outred("$name readSonarDataERROR: $e "   )
								}
								}//if
								
						if(  Distance > 0  
						 ){CommUtils.outyellow("$name with python: data = $data")
						emitLocalStreamEvent("sonardata", "distance($Distance)" ) 
						emit("sonardata", "distance($Distance)" ) 
						}
						forward("doread", "doread(1)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="stopTheSonar",cond=whenDispatch("sonarstop"))
					transition(edgeName="t015",targetState="readSonarData",cond=whenDispatchGuarded("doread",{ working    
					}))
					transition(edgeName="t016",targetState="endOfRead",cond=whenDispatchGuarded("doread",{ ! working  
					}))
				}	 
				state("endOfRead") { //this:State
					action { //it:State
						
									
						   	    p.destroy()
						    	if (p.isAlive()) {
						    	    p.destroyForcibly();
						    	}
						       	CommUtils.outred("$tt $name | endOfRead"  )
									
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="startTheSonar",cond=whenDispatch("sonarstart"))
					transition(edgeName="t018",targetState="stopTheSonar",cond=whenDispatch("sonarstop"))
				}	 
			}
		}
} 
