/* Generated by AN DISI Unibo */ 
package it.unibo.monitoringdevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Monitoringdevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
			var DISTANCE=0
					var DLIMT= 0	
					var FULL= false	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("$name | ready")
						delay(1000) 
						subscribeToLocalActor("datacleaner") 
						delegate("sonarstop", "sonardevice") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="initializing",cond=whenDispatch("sonarstart"))
					transition(edgeName="t01",targetState="endwork",cond=whenDispatch("sonarstop"))
				}	 
				state("initializing") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonarstart(X)"), Term.createTerm("sonarstart(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
								 	   
								 DLIMT=payloadArg(0).toInt()  
								CommUtils.outblack("$name Starting: DLIMT=$DLIMT")
								forward("sonarstart", "sonarstart(1)" ,"sonardevice" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handlesonardata",cond=whenEvent("sonardata"))
					transition(edgeName="t03",targetState="endwork",cond=whenDispatch("sonarstop"))
				}	 
				state("handlesonardata") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 DISTANCE = payloadArg(0).toInt()  
								CommUtils.outyellow("All'inizio il sonar misura $DISTANCE")
								if(  DISTANCE <= DLIMT  
								 ){	FULL = true		 
								CommUtils.outgreen("$name | FULL: $DISTANCE")
								}
								else
								 {	FULL = false	 
								 CommUtils.outgreen("$name | EMPTY: $DISTANCE")
								 }
								emit("updateAS", "updateAS($FULL)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="handlesonardata",cond=whenEvent("sonardata"))
					transition(edgeName="t05",targetState="endwork",cond=whenDispatch("sonarstop"))
				}	 
				state("endwork") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Stop working.")
						forward("sonarstop", "sonarstop(1)" ,"sonardevice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="initializing",cond=whenDispatch("sonarstart"))
				}	 
			}
		}
} 
