/* Generated by AN DISI Unibo */ 
package it.unibo.warningdevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Warningdevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "off"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
			var STATE = 0
				//var runtime = Runtime.getRuntime()
		return { //this:ActionBasciFsm
				state("off") { //this:State
					action { //it:State
						CommUtils.outblack("$name | OFF")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="handleLedStateOne",cond=whenEvent("stateLed"))
				}	 
				state("on") { //this:State
					action { //it:State
						CommUtils.outblack("$name | ON")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="handleLedStateOne",cond=whenEvent("stateLed"))
				}	 
				state("blink") { //this:State
					action { //it:State
						CommUtils.outblack("$name | BLINK")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="handleLedStateOne",cond=whenEvent("stateLed"))
				}	 
				state("handleLedStateOne") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("stateLed(STATE)"), Term.createTerm("stateLed(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 STATE = payloadArg(0).toInt()  
								CommUtils.outyellow("$name | New state: $STATE")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="blink", cond=doswitchGuarded({ STATE == 2 
					}) )
					transition( edgeName="goto",targetState="conditionOnOff", cond=doswitchGuarded({! ( STATE == 2 
					) }) )
				}	 
				state("conditionOnOff") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="on", cond=doswitchGuarded({ STATE == 1  
					}) )
					transition( edgeName="goto",targetState="off", cond=doswitchGuarded({! ( STATE == 1  
					) }) )
				}	 
			}
		}
} 
