/* Generated by AN DISI Unibo */ 
package it.unibo.monitoringdevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Monitoringdevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
			var DISTANCE=0
					var DLIMT= 0	
					var FULL= 0	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("$name | ready")
						delay(2000) 
						subscribeToLocalActor("datacleaner") 
						delegate("sonarstop", "sonardevicemock") 
						delegate("ledOn", "warningdevice") 
						delegate("ledOff", "warningdevice") 
						delegate("ledBlink", "warningdevice") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="initializing",cond=whenDispatch("sonarstart"))
					transition(edgeName="t019",targetState="endwork",cond=whenDispatch("sonarstop"))
				}	 
				state("initializing") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] Starting: DLIMT=$DLIMT")
						if( checkMsgContent( Term.createTerm("sonarstart(X)"), Term.createTerm("sonarstart(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
								 	   
								 DLIMT=payloadArg(0).toInt()  
								delay(5000) 
								forward("sonarstart", "sonarstart(1)" ,"sonardevicemock" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="handlesonardata",cond=whenEvent("sonardatacleaner"))
					transition(edgeName="t021",targetState="endwork",cond=whenDispatch("sonarstop"))
				}	 
				state("handlesonardata") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("sonardatacleaner(DISTANCE)"), Term.createTerm("sonardatacleaner(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 DISTANCE = payloadArg(0).toInt()  
								if(  DISTANCE <= DLIMT  
								 ){	FULL = 1		 
								CommUtils.outgreen("[$name] FULL: $DISTANCE")
								}
								else
								 {	FULL = 0	 
								 CommUtils.outgreen("[$name] EMPTY: $DISTANCE")
								 }
								emit("stateSonar", "stateSonar($FULL)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t022",targetState="handlesonardata",cond=whenEvent("sonardatacleaner"))
					transition(edgeName="t023",targetState="endwork",cond=whenDispatch("sonarstop"))
				}	 
				state("endwork") { //this:State
					action { //it:State
						CommUtils.outmagenta("[$name] Stop working.")
						forward("sonarstop", "sonarstop(1)" ,"sonardevicemock" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="initializing",cond=whenDispatch("sonarstart"))
				}	 
			}
		}
} 
