/* Generated by AN DISI Unibo */ 
package it.unibo.testobserver

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Testobserver ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var ExpectedDistance = -1  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("[$name] in attesa di comandi di test...")
						subscribeToLocalActor("sonarmock") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t042",targetState="handleTestRequest",cond=whenRequest("startTest"))
				}	 
				state("handleTestRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("startTest(PAYLOAD)"), Term.createTerm("startTest(PAYLOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ExpectedDistance = payloadArg(0).toInt()  
								CommUtils.outcyan("[$name] Test avviato. Attendo che la distanza diventi $ExpectedDistance")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t143",targetState="checkSonarValue",cond=whenEvent("stateSonar"))
				}	 
				state("checkSonarValue") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("stateSonar(X)"), Term.createTerm("stateSonar(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val CurrentDistance = payloadArg(0).toInt()  
								CommUtils.outcyan("[$name] Ricevuto evento sonar: $CurrentDistance. Atteso: $ExpectedDistance")
								if(  CurrentDistance == ExpectedDistance  
								 ){answer("startTest", "testReply", "testReply(ok)"   )  
								}
								else
								 {answer("startTest", "testReply", "testReply(ko)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
