/* Generated by AN DISI Unibo */ 
package it.unibo.oprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Oprobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				val pos: MutableMap<String, Array<String>> = mutableMapOf()
			    pos["home"] = arrayOf("0", "0")
			    pos["burnin"] = arrayOf("2", "1")
			    pos["burnout"] = arrayOf("4", "3")
				pos["ashout"] = arrayOf("5", "4")
				pos["wastein"] = arrayOf("0", "4")
		
				var Job=""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] inizializzazione.")
						request("engage", "engage(name,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="standby",cond=whenReply("engagedone"))
				}	 
				state("standby") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] pronto e in attesa in HOME.")
						 Job = "Waiting Home"  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t114",targetState="goWasteIn",cond=whenRequest("bringRP"))
					transition(edgeName="t115",targetState="goBurnOut",cond=whenRequest("bringAsh"))
				}	 
				state("goWasteIn") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] vado in WasteIn.")
						 
						        	val X = pos["wastein"]!!.get(0); 
						        	val Y = pos["wastein"]!!.get(1)
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t216",targetState="goBurnIn",cond=whenReply("moverobotdone"))
					transition(edgeName="t217",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("goBurnIn") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] arrivato in WasteIn, vado in BurnIn.")
						 Job = "In WasteIn"  
						forward("rpTaken", "rpTaken(1)" ,"scalemock" ) 
						 
						        	val X = pos["burnin"]!!.get(0); 
						        	val Y = pos["burnin"]!!.get(1) 
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t318",targetState="arrivedToIncinerator",cond=whenReply("moverobotdone"))
					transition(edgeName="t319",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("arrivedToIncinerator") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] sono arrivato all'inceneritore e notifico.")
						 Job = "Waiting in BurnIn"  
						answer("bringRP", "atIncinerator", "atIncinerator(1)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t420",targetState="goHome",cond=whenDispatch("goHome"))
					transition(edgeName="t421",targetState="goBurnOut",cond=whenRequest("bringAsh"))
					transition(edgeName="t422",targetState="goWasteIn",cond=whenRequest("bringRP"))
				}	 
				state("goHome") { //this:State
					action { //it:State
						if(  Job != "Waiting Home" 
						 ){CommUtils.outyellow("[$name] vado in HOME.")
						 Job = "Going Home"  
						 
						        		val X = pos["home"]!!.get(0); 
						        		val Y = pos["home"]!!.get(1) 
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						}
						else
						 {CommUtils.outyellow("[$name] sono gia' in HOME.")
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="standby", cond=doswitchGuarded({ Job == "Waiting Home"  
					}) )
					transition( edgeName="goto",targetState="waitForReply", cond=doswitchGuarded({! ( Job == "Waiting Home"  
					) }) )
				}	 
				state("waitForReply") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] In attesa di arrivare a HOME...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t523",targetState="standby",cond=whenReply("moverobotdone"))
					transition(edgeName="t524",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("goBurnOut") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] vado a prelevare le ash in BurnOut.")
						 Job = "Going BurnOut"  
						 
						        	val X = pos["burnout"]!!.get(0); 
						        	val Y = pos["burnout"]!!.get(1) 
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t625",targetState="goAshOut",cond=whenReply("moverobotdone"))
					transition(edgeName="t626",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("goAshOut") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] arrivato in BurnOut, vado a depositare in AshOut.")
						 Job = "In BurnOut"  
						 
						        	val X = pos["ashout"]!!.get(0); 
						        	val Y = pos["ashout"]!!.get(1)
						        	 
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t727",targetState="atAshStorage",cond=whenReply("moverobotdone"))
					transition(edgeName="t728",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("atAshStorage") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] arrivato in AshStorage, deposito e notifico.")
						 Job = "Depositing Ashes"  
						forward("newAsh", "newAsh(1)" ,"sonarmock" ) 
						answer("bringAsh", "ashDeposited", "ashDeposited(1)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t829",targetState="goHome",cond=whenDispatch("goHome"))
					transition(edgeName="t830",targetState="goWasteIn",cond=whenRequest("bringRP"))
				}	 
			}
		}
} 
