/* Generated by AN DISI Unibo */ 
package it.unibo.oprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Oprobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				val pos: MutableMap<String, Array<String>> = mutableMapOf()
			    pos["home"] = arrayOf("0", "0")
			    pos["burnin"] = arrayOf("2", "1")
			    pos["burnout"] = arrayOf("4", "3")
				pos["ashout"] = arrayOf("5", "4")
				pos["wastein"] = arrayOf("0", "4")
				
				var Job=""
				var X = 0
				var Y = 0
				
				var X_next = 0
				var Y_next = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] inizializzazione.")
						request("engage", "engage(name,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="standby",cond=whenReply("engagedone"))
				}	 
				state("standby") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] pronto e in attesa in HOME.")
						 
						        	Job = "waitingHome" 
						        	X = pos["home"]!!.get(0).toInt()
						        	Y = pos["home"]!!.get(0).toInt()
						emit("position", "position($X,$Y,$Job)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t18",targetState="goWasteIn",cond=whenRequest("bringRP"))
					transition(edgeName="t19",targetState="goBurnOut",cond=whenRequest("bringAsh"))
				}	 
				state("goWasteIn") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] vado in WasteIn.")
						 
						        	X_next = pos["wastein"]!!.get(0).toInt()
						        	Y_next = pos["wastein"]!!.get(1).toInt()
						        	Job = "goWasteIn" 
						emit("position", "position($X,$Y,$Job)" ) 
						request("moverobot", "moverobot($X_next,$Y_next)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t210",targetState="goBurnIn",cond=whenReply("moverobotdone"))
					transition(edgeName="t211",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("goBurnIn") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] arrivato in WasteIn, vado in BurnIn.")
						 
						        	X = X_next
						        	Y = Y_next
						        	Job = "goBurnIn"
						emit("position", "position($X,$Y,$Job)" ) 
						forward("rpTaken", "rpTaken(1)" ,"scale" ) 
						 
						        	X_next = pos["burnin"]!!.get(0).toInt()
						        	Y_next = pos["burnin"]!!.get(1).toInt()
						request("moverobot", "moverobot($X_next,$Y_next)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t312",targetState="arrivedToIncinerator",cond=whenReply("moverobotdone"))
					transition(edgeName="t313",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("arrivedToIncinerator") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] sono arrivato all'inceneritore e notifico.")
						 
						        	X = X_next
						        	Y = Y_next
						        	Job = "arrivedToIncinerator" 
						emit("position", "position($X,$Y,$Job)" ) 
						answer("bringRP", "atIncinerator", "atIncinerator(1)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t414",targetState="goHome",cond=whenDispatch("goHome"))
					transition(edgeName="t415",targetState="goBurnOut",cond=whenRequest("bringAsh"))
					transition(edgeName="t416",targetState="goWasteIn",cond=whenRequest("bringRP"))
				}	 
				state("goHome") { //this:State
					action { //it:State
						if(  Job != "waitingHome" 
						 ){CommUtils.outgreen("[$name] vado in HOME.")
						 
						        		X = X_next
						        		Y = Y_next
						        		Job = "goHome"
						        		
						        		X_next = pos["home"]!!.get(0).toInt()
						        		Y_next = pos["home"]!!.get(1).toInt() 
						emit("position", "position($X,$Y,$Job)" ) 
						request("moverobot", "moverobot($X_next,$Y_next)" ,"basicrobot" )  
						}
						else
						 {CommUtils.outgreen("[$name] sono gia' in HOME.")
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="standby", cond=doswitchGuarded({ Job == "Waiting Home"  
					}) )
					transition( edgeName="goto",targetState="waitForReply", cond=doswitchGuarded({! ( Job == "Waiting Home"  
					) }) )
				}	 
				state("waitForReply") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] In attesa di arrivare a HOME...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t517",targetState="standby",cond=whenReply("moverobotdone"))
					transition(edgeName="t518",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("goBurnOut") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] vado a prelevare le ash in BurnOut.")
						 
						        	X = X_next
						        	Y = Y_next
						        	Job = "goBurnOut" 
						        	
						        	X_next = pos["burnout"]!!.get(0).toInt() 
						        	Y_next = pos["burnout"]!!.get(1).toInt() 
						emit("position", "position($X,$Y,$Job)" ) 
						request("moverobot", "moverobot($X_next,$Y_next)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t619",targetState="goAshOut",cond=whenReply("moverobotdone"))
					transition(edgeName="t620",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("goAshOut") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] arrivato in BurnOut, vado a depositare in AshOut.")
						 
						        	X = X_next
						        	Y = Y_next
						        	Job = "goAshOut"
						        	
						        	X_next = pos["ashout"]!!.get(0).toInt() 
						        	Y_next = pos["ashout"]!!.get(1).toInt()
						        	 
						emit("position", "position($X,$Y,$Job)" ) 
						request("moverobot", "moverobot($X_next,$Y_next)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t721",targetState="atAshStorage",cond=whenReply("moverobotdone"))
					transition(edgeName="t722",targetState="goHome",cond=whenReply("moverobotfailed"))
				}	 
				state("atAshStorage") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] arrivato in AshStorage, deposito e notifico.")
						 
						        	X = X_next 
						        	X = Y_next
						        	Job = "atAshStorage"
						emit("position", "position($X,$Y,$Job)" ) 
						answer("bringAsh", "ashDeposited", "ashDeposited(1)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t823",targetState="goHome",cond=whenDispatch("goHome"))
					transition(edgeName="t824",targetState="goWasteIn",cond=whenRequest("bringRP"))
				}	 
			}
		}
} 
