/* Generated by AN DISI Unibo */ 
package it.unibo.wis

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Wis ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
			var RP = 0;
				//var ASHVALUE = 100
				var FULL= false
				var INCENERATOR = false
				var ROUTINE = false
				val DLIMT = 30
				var RobotState = "HOME"
				var WEIGHT=0
				var RobotX=""
				var RobotY=""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outgreen("[WIS]$name started")
						subscribeToLocalActor("incenerator") 
						subscribeToLocalActor("scale") 
						subscribeToLocalActor("oprobot") 
						request("cmd", "on(CMD)" ,"incenerator" )  
						forward("sonarstart", "sonarstart($DLIMT)" ,"sonar24" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="waitingCondition",cond=whenReply("ack"))
				}	 
				state("waitingCondition") { //this:State
					action { //it:State
						CommUtils.outgreen("[WIS]Waiting for something")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="verifyCondition",cond=whenEvent("updateWS"))
					transition(edgeName="t019",targetState="verifyCondition",cond=whenEvent("updateAS"))
				}	 
				state("startRoutine") { //this:State
					action { //it:State
						CommUtils.outgreen("[WIS]startRoutine")
						forward("goWasteIn", "go(X)" ,"oprobot" ) 
						 RobotState ="going WasteIn" 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="startIncenerator",cond=whenDispatch("robotArrived"))
					interrupthandle(edgeName="t021",targetState="handleWasteStorage",cond=whenEvent("updateWS"),interruptedStateTransitions)
					interrupthandle(edgeName="t022",targetState="handleAshStorage",cond=whenEvent("updateAS"),interruptedStateTransitions)
					interrupthandle(edgeName="t023",targetState="handleStateRobot",cond=whenEvent("updateStateRobot"),interruptedStateTransitions)
				}	 
				state("startIncenerator") { //this:State
					action { //it:State
							INCENERATOR = true	 
						CommUtils.outgreen("[WIS]start INCENERATOR")
						forward("burn", "burn(X)" ,"incenerator" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="endIncenerator",cond=whenEvent("burnEnd"))
					interrupthandle(edgeName="t025",targetState="handleWasteStorage",cond=whenEvent("updateWS"),interruptedStateTransitions)
					interrupthandle(edgeName="t026",targetState="handleAshStorage",cond=whenEvent("updateAS"),interruptedStateTransitions)
					interrupthandle(edgeName="t027",targetState="handleStateRobot",cond=whenEvent("updateStateRobot"),interruptedStateTransitions)
				}	 
				state("endIncenerator") { //this:State
					action { //it:State
							INCENERATOR = false	 
						CommUtils.outgreen("[WIS]end INCENERATOR")
						forward("goBurnOut", "go(X)" ,"oprobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t028",targetState="endRoutine",cond=whenDispatch("endRoutine"))
					interrupthandle(edgeName="t029",targetState="handleWasteStorage",cond=whenEvent("updateWS"),interruptedStateTransitions)
					interrupthandle(edgeName="t030",targetState="handleAshStorage",cond=whenEvent("updateAS"),interruptedStateTransitions)
					interrupthandle(edgeName="t031",targetState="handleStateRobot",cond=whenEvent("updateStateRobot"),interruptedStateTransitions)
				}	 
				state("endRoutine") { //this:State
					action { //it:State
						CommUtils.outgreen("[WIS]End routine")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="startRoutine", cond=doswitchGuarded({RP>0 && !INCENERATOR && !FULL 
					}) )
					transition( edgeName="goto",targetState="goHome", cond=doswitchGuarded({! (RP>0 && !INCENERATOR && !FULL 
					) }) )
				}	 
				state("goHome") { //this:State
					action { //it:State
						forward("goHome", "go(X)" ,"oprobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingCondition", cond=doswitch() )
				}	 
				state("verifyCondition") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("updateWS(WEIGHT)"), Term.createTerm("updateWS(WEIGHT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("[WIS]handle wastestorage")
									WEIGHT = payloadArg(0).toInt()  
									RP= WEIGHT/50  
								CommUtils.outgreen("RP= $RP")
						}
						if( checkMsgContent( Term.createTerm("updateAS(STATE)"), Term.createTerm("updateAS(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("[CONDITION]handle ashstorage")
								CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
								 	   
								 FULL = payloadArg(0).toBoolean()  
						}
						CommUtils.outgreen("[WIS]verify condition: $RP, $FULL")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="startRoutine", cond=doswitchGuarded({RP>0 && !INCENERATOR && !FULL 
					}) )
					transition( edgeName="goto",targetState="waitingCondition", cond=doswitchGuarded({! (RP>0 && !INCENERATOR && !FULL 
					) }) )
				}	 
				state("handleWasteStorage") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("updateWS(WEIGHT)"), Term.createTerm("updateWS(WEIGHT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("[WIS]handle wastestorage")
									WEIGHT = payloadArg(0).toInt()  
									RP= WEIGHT/50  
								CommUtils.outgreen("RP= $RP")
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleAshStorage") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("updateAS(STATE)"), Term.createTerm("updateAS(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 FULL = payloadArg(0).toBoolean()  
								CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
								 	   
								CommUtils.outgreen("[WIS]handle ashstorage: $FULL")
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleStateRobot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("update(POSX,POSY,JOB)"), Term.createTerm("update(POSX,POSY,JOB)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
									      	RobotX = payloadArg(0)
									        RobotY = payloadArg(1)
									        RobotState = payloadArg(2)
								CommUtils.outgreen("[STATE ROBOT]:	$RobotState	Position:$RobotX,$RobotY")
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
