/* Generated by AN DISI Unibo */ 
package it.unibo.wis

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Wis ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
			val DLIMT = 5
			var wasteStorageWeight=0
			var ashStorageLevel = 0
			var posX = 0
			var posY = 0
			var incinerator = 0
			var job = ""
			var RP=0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] Initializing system")
						subscribeToLocalActor("incinerator") 
						subscribeToLocalActor("scalemock") 
						subscribeToLocalActor("sonarmock") 
						forward("act", "act(2)" ,"incinerator" ) 
						CommUtils.outgreen("[$name] sent act to incinerator")
						 incinerator = 2  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingRP", cond=doswitch() )
				}	 
				state("waitingRP") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] waiting for RP")
						forward("goHome", "goHome(X)" ,"oprobot" ) 
						CommUtils.outgreen("[$name] inviato goHome ad oprobot.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t031",targetState="verifyCondition",cond=whenEvent("stateScale"))
					transition(edgeName="t032",targetState="verifyCondition",cond=whenEvent("stateSonar"))
				}	 
				state("verifyCondition") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outblack("[DEBUG $name] RP=$RP, incineratorState=$incinerator, ashStorageLevel=$ashStorageLevel")
						if( checkMsgContent( Term.createTerm("stateSonar(X)"), Term.createTerm("stateSonar(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ashStorageLevel = payloadArg(0).toInt()  
								CommUtils.outgreen("[$name] Ash storage level updated: $ashStorageLevel")
						}
						if( checkMsgContent( Term.createTerm("stateScale(X)"), Term.createTerm("stateScale(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 	wasteStorageWeight = payloadArg(0).toInt() 
												 RP = wasteStorageWeight/50  
								CommUtils.outgreen("[$name] RP quantity updated: $RP")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="startRoutine", cond=doswitchGuarded({RP>0 && incinerator!=1 && ashStorageLevel > DLIMT 
					}) )
					transition( edgeName="goto",targetState="waitingRP", cond=doswitchGuarded({! (RP>0 && incinerator!=1 && ashStorageLevel > DLIMT 
					) }) )
				}	 
				state("startRoutine") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] start routine")
						request("bringRP", "bringRP(X)" ,"oprobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t033",targetState="startIncinerator",cond=whenReply("atIncinerator"))
					interrupthandle(edgeName="t034",targetState="handleStateScale",cond=whenEvent("stateScale"),interruptedStateTransitions)
					interrupthandle(edgeName="t035",targetState="handleStateSonar",cond=whenEvent("stateSonar"),interruptedStateTransitions)
				}	 
				state("startIncinerator") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] Incinerator started")
						forward("notifyRp", "notifyRp(X)" ,"incinerator" ) 
						forward("goHome", "goHome(X)" ,"oprobot" ) 
						 incinerator = 1 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t036",targetState="endIncinerator",cond=whenEvent("burnEnd"))
					interrupthandle(edgeName="t037",targetState="handleStateScale",cond=whenEvent("stateScale"),interruptedStateTransitions)
					interrupthandle(edgeName="t038",targetState="handleStateSonar",cond=whenEvent("stateSonar"),interruptedStateTransitions)
				}	 
				state("endIncinerator") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] incinerator is now idle")
						request("bringAsh", "bringAsh(X)" ,"oprobot" )  
						 
						    		incinerator = 2
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t039",targetState="verifyCondition",cond=whenReply("ashDeposited"))
					interrupthandle(edgeName="t040",targetState="handleStateScale",cond=whenEvent("stateScale"),interruptedStateTransitions)
					interrupthandle(edgeName="t041",targetState="handleStateSonar",cond=whenEvent("stateSonar"),interruptedStateTransitions)
				}	 
				state("handleStateSonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stateSonar(X)"), Term.createTerm("stateSonar(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ashStorageLevel = payloadArg(0).toInt()  
								CommUtils.outgreen("[$name] Ash storage level updated: $ashStorageLevel")
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleStateScale") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stateScale(X)"), Term.createTerm("stateScale(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 	wasteStorageWeight = payloadArg(0).toInt() 
												RP = wasteStorageWeight/50  
								CommUtils.outgreen("[$name] RP quantity updated: $RP")
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
