# Server Configuration
server.port=8080
spring.application.name=wisfacade

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.root=INFO
logging.level.it.unibo.wis=DEBUG

# Static Resources
spring.web.resources.static-locations=classpath:/static/
