/* Generated by AN DISI Unibo */ 
package it.unibo.sonardevicemock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonardevicemock ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
			var DISTANCE=200
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] inizializzazione.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="start",cond=whenDispatch("sonarstart"))
				}	 
				state("start") { //this:State
					action { //it:State
						CommUtils.outgreen("[$name] sonardata updated: $DISTANCE.")
						emitLocalStreamEvent("sonardevicedata", "sonardevicedata($DISTANCE)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="handleNewAsh",cond=whenDispatch("newAsh"))
					transition(edgeName="t02",targetState="handleEmptyAsh",cond=whenDispatch("emptyAsh"))
				}	 
				state("handleNewAsh") { //this:State
					action { //it:State
						DISTANCE = DISTANCE - 60 
						CommUtils.outgreen("[$name] sonardata updated: $DISTANCE.")
						emitLocalStreamEvent("sonardevicedata", "sonardevicedata($DISTANCE)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handleNewAsh",cond=whenDispatch("newAsh"))
					transition(edgeName="t04",targetState="handleEmptyAsh",cond=whenDispatch("emptyAsh"))
				}	 
				state("handleEmptyAsh") { //this:State
					action { //it:State
						DISTANCE = 200 
						CommUtils.outgreen("[$name] ashes svuotate. sonardata updated: $DISTANCE.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="handleNewAsh",cond=whenDispatch("newAsh"))
					transition(edgeName="t06",targetState="handleEmptyAsh",cond=whenDispatch("emptyAsh"))
				}	 
			}
		}
} 
